### ISSUE TITLE
Trouble with sb-shim on openSUSE

### ISSUE THREAD

**Issue by geckolinux** [calamares/calamares#2033]
Hi everyone, I'm giving `sb-shim` another attempt (after failing in #1484) to install a system based on openSUSE Leap 15.4 with Calamares 3.2.59.

It's still failing, but with different errors now. Here's the most relevant part:

```
.. Job description from pretty_name "bootloader" = "Install bootloader." 
Could not prepare Boot variable: No such file or directory
[...]
    ERROR: Installation failed: "Boost.Python error in job \"bootloader\"." 
    .. - message: "Boost.Python error in job \"bootloader\"." 
    .. - details: <div><strong>&lt;class 'TypeError'&gt;</strong></div><div>__init__() got an unexpected keyword argument 'text'</div><div><br/>Traceback:</div><div><pre>File &quot;/usr/lib64/calamares/modules/bootloader/main.py&quot;, line 777, in run
    prepare_bootloader(fw_type)
```

Here's the full [log](https://github.com/calamares/calamares/files/9242866/calamares.log.txt) , and this is the [bootloader.conf](https://github.com/calamares/calamares/files/9242873/bootloader.conf.txt) that was used. Can anybody point me in the right direction about what I'm doing wrong? Thanks a lot!

**Comment by adriaandegroot** [comment]
Here's the full traceback from the log:

```
08:52:56 [1]: void Calamares::ViewManager::onInstallationFailed(const QString&, const
 QString&)
    ERROR: Installation failed: "Boost.Python error in job \"bootloader\"." 
    .. - message: "Boost.Python error in job \"bootloader\"." 
    .. - details: <div><strong>&lt;class 'TypeError'&gt;</strong></div><div>__init__(
) got an unexpected keyword argument 'text'</div><div><br/>Traceback:</div><div><pre>
File &quot;/usr/lib64/calamares/modules/bootloader/main.py&quot;, line 777, in run
    prepare_bootloader(fw_type)

  File &quot;/usr/lib64/calamares/modules/bootloader/main.py&quot;, line 746, in prep
are_bootloader
    install_secureboot(efi_directory)

  File &quot;/usr/lib64/calamares/modules/bootloader/main.py&quot;, line 715, in inst
all_secureboot
    efi_boot_next()

  File &quot;/usr/lib64/calamares/modules/bootloader/main.py&quot;, line 457, in efi_
boot_next
    efi_bootvars = subprocess.check_output([boot_mgr], text=True)

  File &quot;/usr/lib64/python3.6/subprocess.py&quot;, line 356, in check_output
    **kwargs).stdout

  File &quot;/usr/lib64/python3.6/subprocess.py&quot;, line 423, in run
    with Popen(*popenargs, **kwargs) as process:</pre></div>
```

**Comment by adriaandegroot** [comment]
@geckolinux What Python version are you using? Oh, 3.6 :) The *text* parameter was added only in 3.7, so we'll need to patch it back to the less-readable *universal_newlines*.

**Comment by geckolinux** [comment]
@adriaandegroot Ahh, thanks! Never would have figured that one out. :)

**Comment by adriaandegroot** [comment]
This will need a release to get to you conveniently, or grab that one commit as a patch. The underlying problem is one of Python versions: 3.3 uses *universal_newlines*, in 3.7 *text* was added and the old name re-labeled as "backwards compatibility name", and none of the Calamares branches requires Python 3.7. Almost all development happens on platforms with newer Pythons, though.

**Comment by geckolinux** [comment]
Thanks very much, I'll probably cherry pick that patch.
